### ISSUE TITLE
Break crate into many tiny features

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing_2d#20]
Important for inclusion in leafwing_input_manager.

**Comment by alice-i-cecile** [comment]
Breaking apart the bundle is blocked on https://github.com/rust-analyzer/rust-analyzer/issues/11661

**Comment by alice-i-cecile** [comment]
Initial breakdown:

```toml
[features]
default = ["plugin", "bundles", "bounding"]
plugin = ["systems"]
bundles = ["orientation", "position", "kinematics", "continuous", "discrete"]
systems = []
orientation = []
position = []
kinematics = []
bounding = []
continuous = []
discrete = []
```
